name: CI

on:
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: .
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: true
          extra-black-options: "--diff --fast"
          use-isort: true
          use-mypy: true
          extra-mypy-options: "--strict"
      #
      # - name: Set up Python 3.6
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.6.15
      #
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install flake8 pytest pytest-cov
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
