name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.13

      - name: set pythonpath
        run: echo "PYTHONPATH=${PYTHONPATH}:$(pwd)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install black flake8 mypy pytest

      - name: execute flake8
        run: flake8 .

      - name: execute black
        run: black --check --diff --fast .

      - name: execute mypy
        run: mypy --strict .

      - name: execute pytest
        run: pytest
