name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: python:${{matrix.python-version}}, flake8:${{matrix.flake8-version}}
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
        flake8-version:
          - '3.9.2'
          - '4.0.1'
          - '5.0.4'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
          architecture: x64
      - name: set pythonpath
        run: echo "PYTHONPATH=${PYTHONPATH}:$(pwd)" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install black mypy pytest xenon 'flake8==${{matrix.flake8-version}}'
      - name: execute flake8
        run: flake8 .
      - name: execute black
        run: black --check --diff --fast .
      - name: execute mypy
        run: mypy --strict .
      - name: execute pytest
        run: pytest
      - name: execute Xenon
        run: xenon -max-absolute B --max-modules A --max-average A
